<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>AI Disclaimer | The Offer Company</title>
  <style>
    body {
      font-family: Arial, sans-serif;
      line-height: 1.6;
      max-width: 800px;
      margin: 40px auto;
      padding: 0 20px;
      color: #333;
    }
    h1, h2 {
      color: #222;
    }
    h1 {
      font-size: 2em;
      margin-bottom: 0.5em;
    }
    h2 {
      font-size: 1.25em;
      margin-top: 1.5em;
    }
    table {
      width: 100%;
      border-collapse: collapse;
      margin-top: 1em;
    }
    th, td {
      border: 1px solid #ccc;
      padding: 10px;
      text-align: left;
    }
    th {
      background-color: #f9f9f9;
    }
    a {
      color: #0066cc;
    }
    .footer {
      margin-top: 2em;
      font-size: 0.9em;
      color: #777;
    }
  </style>
</head>
<body>

  <h1>AI Disclaimer – The Offer Company</h1>
  <p><strong>Last Updated:</strong> June 12, 2025</p>

  <h2>1. Scope & Acceptance</h2>
  <p>This AI Disclaimer applies to every interaction you have with The Offer Company’s artificial intelligence assistant, <strong>Hope</strong> — including voice or text chats, automated messages, appointment scheduling, and any AI-generated information, suggestions, or guidance (collectively, “AI Content”).
  By using Hope, you agree to this Disclaimer and to The Offer Company’s <a href="/terms-of-service">Terms of Service</a> and <a href="/privacy">Privacy Policy</a>. If you do not accept any part of these terms, you should not use the AI features provided.</p>

  <h2>2. Nature of the AI Service</h2>
  <ul>
    <li>Hope is a conversational AI designed to assist homeowners in Arizona with understanding their options in foreclosure situations.</li>
    <li>AI Content is generated by large language models and is for <strong>informational purposes only</strong>.</li>
    <li>Hope is <strong>not</strong> a licensed real estate agent, legal professional, or financial advisor.</li>
    <li>Any guidance provided by Hope is <strong>not a substitute</strong> for personalized advice from a licensed professional.</li>
    <li>The technology may occasionally generate <strong>incomplete, outdated, or inaccurate responses</strong>.</li>
  </ul>

  <h2>3. No Professional–Client Relationship</h2>
  <p>Using Hope does <strong>not</strong> create a client, broker, agent, legal, or fiduciary relationship.</p>
  <ul>
    <li>Hope is not a licensed real estate broker or attorney.</li>
    <li>Any interactions with Hope do <strong>not constitute legal advice</strong>, real estate representation, or financial counseling.</li>
    <li>For specific guidance on foreclosure, loan modifications, or real estate sales, users should consult a licensed professional.</li>
  </ul>

  <h2>4. Limitations & Known Risks</h2>
  <table>
    <tr>
      <th>Limitation</th>
      <th>Explanation</th>
    </tr>
    <tr>
      <td>Knowledge Cutoff</td>
      <td>Hope may not reflect recent changes to Arizona foreclosure laws or market conditions.</td>
    </tr>
    <tr>
      <td>Context Gaps</td>
      <td>Hope may misunderstand unclear questions, tone, or intent.</td>
    </tr>
    <tr>
      <td>No Legal Accuracy Guarantee</td>
      <td>AI responses are not legally binding and should not be relied upon for critical decisions.</td>
    </tr>
    <tr>
      <td>Potential Bias</td>
      <td>AI may reflect biases present in training data.</td>
    </tr>
    <tr>
      <td>Response Variability</td>
      <td>Responses may vary between sessions or users.</td>
    </tr>
  </table>

  <h2>5. User Responsibilities</h2>
  <ul>
    <li><strong>Use Critical Judgment</strong> – Treat AI Content as general guidance only.</li>
    <li><strong>Consult Professionals</strong> – Always speak with a licensed real estate agent or attorney before making time-sensitive or financially significant decisions.</li>
    <li><strong>Be Honest</strong> – Accurate input will lead to more relevant (though not guaranteed accurate) responses.</li>
    <li><strong>Report Issues</strong> – If you receive a harmful or inappropriate response, contact us at <a href="mailto:support@theofferco.com">support@theofferco.com</a>.</li>
  </ul>

  <h2>6. Data Handling & Privacy</h2>
  <ul>
    <li>Conversations with Hope may be logged and reviewed to improve system functionality and ensure compliance.</li>
    <li>Data collected through interactions is used to provide services and maintain quality but <strong>is not used to train external AI models</strong>.</li>
    <li>For full details, please refer to our <a href="/privacy">Privacy Policy</a>.</li>
  </ul>

  <h2>7. Human Oversight</h2>
  <ul>
    <li>While Hope automates initial communication, any property offers, contracts, or service agreements will always involve a licensed broker from The Offer Company.</li>
    <li>You may request human follow-up at any time during your interaction.</li>
    <li>We do not monitor every AI interaction in real-time and cannot guarantee live oversight.</li>
  </ul>

  <h2>8. Limitation of Liability</h2>
  <p>To the fullest extent permitted by law, The Offer Company, its owners, employees, partners, affiliates, and licensors shall not be liable for any damages or losses related to:</p>
  <ul>
    <li>Reliance on AI-generated content</li>
    <li>Delays in seeking professional advice</li>
    <li>Misunderstandings or errors in AI responses</li>
    <li>Service outages, interruptions, or unavailability</li>
    <li>Any transaction, decision, or communication made based on Hope’s responses</li>
  </ul>
  <p>All disclaimers and limitations of liability in our <a href="/terms-of-service">Terms of Service</a> apply here in full.</p>

  <h2>9. Updates to This Disclaimer</h2>
  <p>This Disclaimer may be updated periodically to reflect changes in the AI system, legal standards, or our service model.
  Continued use of Hope after updates constitutes acceptance of the new terms.</p>

  <h2>10. Contact</h2>
  <p><strong>The Offer Company</strong><br>
  Attn: Legal / AI Risk Management<br>
  4802 E. Ray Road, Phoenix, AZ 85044<br>
  📧 <a href="mailto:support@theofferco.com">support@theofferco.com</a><br>
  📞 602-448-7377</p>

  <div class="footer">© 2025 The Offer Company. All rights reserved.</div>

</body>
</html>
